#!/usr/bin/env node
// Copies the ABIs of the contracts from the Hardhat artifacts to src/abi, as typed
// TypeScript constants. Run it after compiling the contracts, whenever one of them changes.
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const CONTRACTS = ["MultiChainTxRegistry", "FundRegistry", "OrderRegistry", "MultiChainTxReceiver"];

for (const name of CONTRACTS) {
  const artifact = new URL(`../../smart-contracts/artifacts/contracts/${name}.sol/${name}.json`, import.meta.url);
  if (!existsSync(artifact)) {
    console.error(`Artifact of ${name} not found. Compile the contracts first: cd smart-contracts; npx hardhat build`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  const constant = name[0].toLowerCase() + name.slice(1) + "Abi";
  const source =
    `// Generated by scripts/sync-abi.mjs from the Hardhat artifact of ${name}. Do not edit.\n` +
    `export const ${constant} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(new URL(`../src/abi/${name}.ts`, import.meta.url), source);
  console.log(`src/abi/${name}.ts: ${abi.length} entries`);
}
